// ************ Get the countries from "a" that are not avialable in "b" ******************

// var a = [
//   "Afghanistan",
//   "Albania",
//   "Algeria",
//   "American Samoa",
//   "Andorra",
//   "Angola",
//   "Anguilla",
//   "Antigua And Barbuda",
//   "Argentina",
//   "Armenia",
//   "Aruba",
//   "Australia",
//   "Austria",
//   "Azerbaijan",
//   "Bahamas",
//   "Bahrain",
//   "Bangladesh",
//   "Barbados",
//   "Belarus",
//   "Belgium",
//   "Belize",
//   "Benin",
//   "Bermuda",
//   "Bhutan",
//   "Bolivia",
//   "Bonaire",
//   "Bosnia and Herzegovina",
//   "Botswana",
//   "Brazil",
//   "British Indian Ocean Territory",
//   "Brunei",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burundi",
//   "Cambodia",
//   "Cameroon",
//   "Canada",
//   "Cape Verde",
//   "Cayman Islands",
//   "Central African Republic",
//   "Channel Islands",
//   "Chad",
//   "Chile",
//   "Christmas Island",
//   "China",
//   "Cocos Island",
//   "Colombia",
//   "Comoros",
//   "Congo",
//   "Congo The Democratic Republic Of The",
//   "Cook Island",
//   "Costa Rica",
//   "Cote D'Ivoire (Ivory Coast)",
//   "Croatia (Hrvatska)",
//   "Cuba",
//   "Central African Republic",
//   "Curaco",
//   "Cyprus",
//   "Czech Republic",
//   "Denmark",
//   "Djibouti",
//   "Dominica",
//   "Dominican Republic",
//   "East Timor",
//   "Ecuador",
//   "Egypt",
//   "El Salvador",
//   "Equatorial Guinea",
//   "Eritrea",
//   "Estonia",
//   "Ethiopia",
//   "Falkland Island",
//   "Faroe Islands",
//   "Fiji Islands",
//   "Finland",
//   "France",
//   "French Guiana",
//   "French Polynesia",
//   "French Southern Territories",
//   "Gabon",
//   "Gambia The",
//   "Georgia",
//   "Germany",
//   "Ghana",
//   "Gibraltar",
//   "Greece",
//   "Greenland",
//   "Grenada",
//   "Guadeloupe",
//   "Guam",
//   "Guatemala",
//   "Guinea",
//   "Guinea-Bissau",
//   "Guyana",
//   "Haiti",
//   "Honduras",
//   "Hong Kong S.A.R.",
//   "Hungary",
//   "Iceland",
//   "India",
//   "Indonesia",
//   "Iran",
//   "Iraq",
//   "Isle of Man",
//   "Ireland",
//   "Israel",
//   "Italy",
//   "Jamaica",
//   "Japan",
//   "Jordan",
//   "Kazakhstan",
//   "Kenya",
//   "Kiribati",
//   "Korea North",
//   "Korea South",
//   "Kosovo",
//   "Kuwait",
//   "Kyrgyzstan",
//   "Laos",
//   "Latvia",
//   "Lebanon",
//   "Lesotho",
//   "Liberia",
//   "Libya",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Macau S.A.R",
//   "Macedonia",
//   "Madagascar",
//   "Malawi",
//   "Malaysia",
//   "Maldives",
//   "Mali",
//   "Malta",
//   "Marshall Islands",
//   "Martinique",
//   "Mauritania",
//   "Mauritius",
//   "Mexico",
//   "Micronesia",
//   "Moldova",
//   "Monaco",
//   "Mongolia",
//   "Montenegro",
//   "Montserrat",
//   "Morocco",
//   "Mozambique",
//   "Myanmar",
//   "Namibia",
//   "Nauru",
//   "Nepal",
//   "Netherland Antilles",
//   "Netherlands The",
//   "New Caledonia",
//   "New Zealand",
//   "Nicaragua",
//   "Niger",
//   "Nigeria",
//   "Niue",
//   "Norfolk Island",
//   "Norway",
//   "Oman",
//   "Pakistan",
//   "Palau",
//   "Palestinian ",
//   "Panama",
//   "Papua new Guinea",
//   "Paraguay",
//   "Peru",
//   "Philippines",
//   "Palestine",
//   "Pitcairn Island",
//   "Puerto Rico",
//   "Poland",
//   "Portugal",
//   "Qatar",
//   "Republic of Serbia",
//   "Republic of Montenegro",
//   "Reunion",
//   "Romania",
//   "Russia",
//   "Rwanda",
//   "Saint Helena",
//   "Saint Kitts And Nevis",
//   "Saint Lucia",
//   "Saint Pierre and Miquelon",
//   "Saint Vincent And The Grenadines",
//   "St Pierre & Miquelon",
//   "Saipan",
//   "Saint-Barthelemy",
//   "Saint-Martin (French part)",
//   "Samoa",
//   "San Marino",
//   "Sao Tome and Principe",
//   "Saudi Arabia",
//   "Senegal",
//   "Serbia",
//   "Seychelles",
//   "Sierra Leone",
//   "Singapore",
//   "Slovakia",
//   "St Maarten",
//   "St Eustatius",
//   "St Helena",
//   "Slovenia",
//   "Solomon Islands",
//   "Somalia",
//   "South Africa",
//   "South Sudan",
//   "Spain",
//   "Sri Lanka",
//   "Sudan",
//   "Suriname",
//   "Swaziland",
//   "Sweden",
//   "Switzerland",
//   "Syria",
//   "Taiwan",
//   "Tajikistan",
//   "Tanzania",
//   "Thailand",
//   "Togo",
//   "Samoa American",
//   "Tahiti",
//   "Tokelau",
//   "Tonga",
//   "Trinidad And Tobago",
//   "Tunisia",
//   "Turkey",
//   "Turkmenistan",
//   "Turks & Caicos Is",
//   "Tuvalu",
//   "Uganda",
//   "Ukraine",
//   "United Arab Emirates",
//   "United Kingdom",
//   "United States",
//   "Uruguay",
//   "Uzbekistan",
//   "Vanuatu",
//   "Vatican City State",
//   "Venezuela",
//   "Vietnam",
//   "Virgin Islands (Brit)",
//   "Virgin Islands (USA)",
//   "Wake Island",
//   "Wallis & Futana Islands",
//   "Zaire",
//   "Yemen",
//   "Zambia",
//   "Zimbabwe",
// ];

// var b = [
//   "land Islands",
//   "Afghanistan",
//   "Akrotiri",
//   "Albania",
//   "Algeria",
//   "American Samoa",
//   "Andorra",
//   "Angola",
//   "Anguilla",
//   "Antarctica",
//   "Antigua and Barbuda",
//   "Argentina",
//   "Armenia",
//   "Aruba",
//   "Ashmore and Cartier Islands",
//   "Australia",
//   "Austria",
//   "Azerbaijan",
//   "Bahrain",
//   "Bangladesh",
//   "Barbados",
//   "Bassas Da India",
//   "Belarus",
//   "Belgium",
//   "Belize",
//   "Benin",
//   "Bermuda",
//   "Bhutan",
//   "Bolivia",
//   "Bosnia and Herzegovina",
//   "Botswana",
//   "Bouvet Island",
//   "Brazil",
//   "British Indian Ocean Territory",
//   "British Virgin Islands",
//   "Brunei",
//   "Bulgaria",
//   "Burkina Faso",
//   "Burma",
//   "Burundi",
//   "Cambodia",
//   "Cameroon",
//   "Canada",
//   "Cape Verde",
//   "Caribbean Netherlands",
//   "Cayman Islands",
//   "Central African Republic",
//   "Chad",
//   "Chile",
//   "China",
//   "Christmas Island",
//   "Clipperton Island",
//   "Cocos Keeling&#x29; Islands",
//   "Colombia",
//   "Comoros",
//   "Cook Islands",
//   "Coral Sea Islands",
//   "Costa Rica",
//   "Cote D&#x27;Ivoire",
//   "Croatia",
//   "Cuba",
//   "Cura&ccedil;ao",
//   "Cyprus",
//   "Czech Republic",
//   "Democratic Republic of the Congo",
//   "Denmark",
//   "Dhekelia",
//   "Djibouti",
//   "Dominica",
//   "Dominican Republic",
//   "Ecuador",
//   "Egypt",
//   "El Salvador",
//   "Equatorial Guinea",
//   "Eritrea",
//   "Estonia",
//   "Ethiopia",
//   "Europa Island",
//   "Falkland Islands Islas Malvinas&#x29;",
//   "Faroe Islands",
//   "Federated States of Micronesia",
//   "Fiji",
//   "Finland",
//   "France",
//   "French Guiana",
//   "French Polynesia",
//   "French Southern and Antarctic Lands",
//   "Gabon",
//   "Gaza Strip",
//   "Georgia",
//   "Germany",
//   "Ghana",
//   "Gibraltar",
//   "Glorioso Islands",
//   "Greece",
//   "Greenland",
//   "Grenada",
//   "Guadeloupe",
//   "Guam",
//   "Guatemala",
//   "Guernsey",
//   "Guinea",
//   "Guinea-bissau",
//   "Guyana",
//   "Haiti",
//   "Heard Island and Mcdonald Islands",
//   "Holy See Vatican City&#x29;",
//   "Honduras",
//   "Hong Kong",
//   "Hungary",
//   "Iceland",
//   "India",
//   "Indonesia",
//   "Iran",
//   "Iraq",
//   "Ireland",
//   "Isle of Man",
//   "Israel",
//   "Italy",
//   "Jamaica",
//   "Jan Mayen",
//   "Japan",
//   "Jersey",
//   "Jordan",
//   "Juan De Nova Island",
//   "Kazakhstan",
//   "Kenya",
//   "Kiribati",
//   "Kosovo",
//   "Kuwait",
//   "Kyrgyzstan",
//   "Laos",
//   "Latvia",
//   "Lebanon",
//   "Lesotho",
//   "Liberia",
//   "Libya",
//   "Liechtenstein",
//   "Lithuania",
//   "Luxembourg",
//   "Macau",
//   "Macedonia",
//   "Madagascar",
//   "Malawi",
//   "Malaysia",
//   "Maldives",
//   "Mali",
//   "Malta",
//   "Marshall Islands",
//   "Martinique",
//   "Mauritania",
//   "Mauritius",
//   "Mayotte",
//   "Mexico",
//   "Moldova",
//   "Monaco",
//   "Mongolia",
//   "Montenegro",
//   "Montserrat",
//   "Morocco",
//   "Mozambique",
//   "Myanmar",
//   "Namibia",
//   "Nauru",
//   "Navassa Island",
//   "Nepal",
//   "Netherlands",
//   "Netherlands Antilles",
//   "New Caledonia",
//   "New Zealand",
//   "Nicaragua",
//   "Niger",
//   "Nigeria",
//   "Niue",
//   "Norfolk Island",
//   "North Korea",
//   "Northern Mariana Islands",
//   "Norway",
//   "Oman",
//   "Pakistan",
//   "Palau",
//   "Palestine",
//   "Panama",
//   "Papua New Guinea",
//   "Paracel Islands",
//   "Paraguay",
//   "Peru",
//   "Philippines",
//   "Pitcairn Islands",
//   "Poland",
//   "Portugal",
//   "Puerto Rico",
//   "Qatar",
//   "Republic of the Congo",
//   "Reunion",
//   "Romania",
//   "Russia",
//   "Rwanda",
//   "Saint Barth&Atilde;&copy;lemy",
//   "Saint Helena",
//   "Saint Kitts and Nevis",
//   "Saint Lucia",
//   "Saint Martin",
//   "Saint Pierre and Miquelon",
//   "Saint Vincent and the Grenadines",
//   "Samoa",
//   "San Marino",
//   "Sao Tome and Principe",
//   "Saudi Arabia",
//   "Senegal",
//   "Serbia",
//   "Seychelles",
//   "Sierra Leone",
//   "Singapore",
//   "Sint Maarten",
//   "Slovakia",
//   "Slovenia",
//   "Solomon Islands",
//   "Somalia",
//   "South Africa",
//   "South Georgia and the South Sandwich Islands",
//   "South Korea",
//   "South Sudan",
//   "Spain",
//   "Spratly Islands",
//   "Sri Lanka",
//   "Sudan",
//   "Suriname",
//   "Svalbard",
//   "Swaziland",
//   "Sweden",
//   "Switzerland",
//   "Syria",
//   "Taiwan",
//   "Tajikistan",
//   "Tanzania",
//   "Thailand",
//   "The Bahamas",
//   "The Gambia",
//   "Timor-leste",
//   "Togo",
//   "Tokelau",
//   "Tonga",
//   "Trinidad and Tobago",
//   "Tromelin Island",
//   "Tunisia",
//   "Turkey",
//   "Turkmenistan",
//   "Turks and Caicos Islands",
//   "Tuvalu",
//   "Uganda",
//   "Ukraine",
//   "United Arab Emirates",
//   "United Kingdom",
//   "United States",
//   "Uruguay",
//   "Uzbekistan",
//   "Vanuatu",
//   "Venezuela",
//   "Vietnam",
//   "Virgin Islands",
//   "Wake Island",
//   "Wallis and Futuna",
//   "West Bank",
//   "Western Sahara",
//   "Yemen",
//   "Zambia",
//   "Zimbabwe",
// ];
// var final = b.filter((item) => {
//   return !a.includes(item);
// });

// console.log(final);

// ******************* Get countries which has states only ***********************

// var countries1 = {
//   Aruba: "ABW",
//   Afghanistan: "AFG",
//   Angola: "AGO",
//   Anguilla: "AIA",
//   "Aland Islands !Åland Islands": "ALA",
//   Albania: "ALB",
//   Andorra: "AND",
//   "Not Found": "ANT",
//   "United Arab Emirates": "ARE",
//   Argentina: "ARG",
//   Armenia: "ARM",
//   "American Samoa": "ASM",
//   Antarctica: "ATA",
//   "French Southern Territories": "ATF",
//   "Antigua and Barbuda": "ATG",
//   Australia: "AUS",
//   Austria: "AUT",
//   Azerbaijan: "AZE",
//   Burundi: "BDI",
//   Belgium: "BEL",
//   Benin: "BEN",
//   "Bonaire, Sint Eustatius and Saba": "BES",
//   "Burkina Faso": "BFA",
//   Bangladesh: "BGD",
//   Bulgaria: "BGR",
//   Bahrain: "BHR",
//   Bahamas: "BHS",
//   "Bosnia and Herzegovina": "BIH",
//   "Saint Barthelemy !Saint Barthélemy": "BLM",
//   Belarus: "BLR",
//   Belize: "BLZ",
//   Bermuda: "BMU",
//   "Bolivia (Plurinational State of)": "BOL",
//   Brazil: "BRA",
//   Barbados: "BRB",
//   "Brunei Darussalam": "BRN",
//   Bhutan: "BTN",
//   "Bouvet Island": "BVT",
//   Botswana: "BWA",
//   "Central African Republic": "CAF",
//   Canada: "CAN",
//   "Cocos (Keeling) Islands": "CCK",
//   Switzerland: "CHE",
//   Chile: "CHL",
//   China: "CHN",
//   "Cote d'Ivoire !Côte d'Ivoire": "CIV",
//   Cameroon: "CMR",
//   "Congo (Democratic Republic of the)": "COD",
//   Congo: "COG",
//   "Cook Islands": "COK",
//   Colombia: "COL",
//   Comoros: "COM",
//   "Cabo Verde": "CPV",
//   "Costa Rica": "CRI",
//   Cuba: "CUB",
//   "Curacao !Curaçao": "CUW",
//   "Christmas Island": "CXR",
//   "Cayman Islands": "CYM",
//   Cyprus: "CYP",
//   "Czech Republic": "CZE",
//   Germany: "DEU",
//   Djibouti: "DJI",
//   Dominica: "DMA",
//   Denmark: "DNK",
//   "Dominican Republic": "DOM",
//   Algeria: "DZA",
//   Ecuador: "ECU",
//   Egypt: "EGY",
//   Eritrea: "ERI",
//   Spain: "ESP",
//   Estonia: "EST",
//   Ethiopia: "ETH",
//   Finland: "FIN",
//   Fiji: "FJI",
//   "Falkland Islands (Malvinas)": "FLK",
//   France: "FRA",
//   "Faroe Islands": "FRO",
//   "Micronesia (Federated States of)": "FSM",
//   Gabon: "GAB",
//   "United Kingdom of Great Britain and Northern Ireland": "GBR",
//   Georgia: "GEO",
//   Guernsey: "GGY",
//   Ghana: "GHA",
//   Gibraltar: "GIB",
//   Guinea: "GIN",
//   Guadeloupe: "GLP",
//   Gambia: "GMB",
//   "Guinea-Bissau": "GNB",
//   "Equatorial Guinea": "GNQ",
//   Greece: "GRC",
//   Grenada: "GRD",
//   Greenland: "GRL",
//   Guatemala: "GTM",
//   "French Guiana": "GUF",
//   Guam: "GUM",
//   Guyana: "GUY",
//   "Hong Kong": "HKG",
//   "Heard Island and McDonald Islands": "HMD",
//   Honduras: "HND",
//   Croatia: "HRV",
//   Haiti: "HTI",
//   Hungary: "HUN",
//   Indonesia: "IDN",
//   "Isle of Man": "IMN",
//   India: "IND",
//   "British Indian Ocean Territory": "IOT",
//   Ireland: "IRL",
//   "Iran (Islamic Republic of)": "IRN",
//   Iraq: "IRQ",
//   Iceland: "ISL",
//   Israel: "ISR",
//   Italy: "ITA",
//   Jamaica: "JAM",
//   Jersey: "JEY",
//   Jordan: "JOR",
//   Japan: "JPN",
//   Kazakhstan: "KAZ",
//   Kenya: "KEN",
//   Kyrgyzstan: "KGZ",
//   Cambodia: "KHM",
//   Kiribati: "KIR",
//   "Saint Kitts and Nevis": "KNA",
//   "Korea (Republic of)": "KOR",
//   Kuwait: "KWT",
//   "Lao People's Democratic Republic": "LAO",
//   Lebanon: "LBN",
//   Liberia: "LBR",
//   Libya: "LBY",
//   "Saint Lucia": "LCA",
//   Liechtenstein: "LIE",
//   "Sri Lanka": "LKA",
//   Lesotho: "LSO",
//   Lithuania: "LTU",
//   Luxembourg: "LUX",
//   Latvia: "LVA",
//   Macao: "MAC",
//   "Saint Martin (French part)": "MAF",
//   Morocco: "MAR",
//   Monaco: "MCO",
//   "Moldova (Republic of)": "MDA",
//   Madagascar: "MDG",
//   Maldives: "MDV",
//   Mexico: "MEX",
//   "Marshall Islands": "MHL",
//   "Macedonia (the former Yugoslav Republic of)": "MKD",
//   Mali: "MLI",
//   Malta: "MLT",
//   Myanmar: "MMR",
//   Montenegro: "MNE",
//   Mongolia: "MNG",
//   "Northern Mariana Islands": "MNP",
//   Mozambique: "MOZ",
//   Mauritania: "MRT",
//   Montserrat: "MSR",
//   Martinique: "MTQ",
//   Mauritius: "MUS",
//   Malawi: "MWI",
//   Malaysia: "MYS",
//   Mayotte: "MYT",
//   Namibia: "NAM",
//   "New Caledonia": "NCL",
//   Niger: "NER",
//   "Norfolk Island": "NFK",
//   Nigeria: "NGA",
//   Nicaragua: "NIC",
//   Niue: "NIU",
//   Netherlands: "NLD",
//   Norway: "NOR",
//   Nepal: "NPL",
//   Nauru: "NRU",
//   "New Zealand": "NZL",
//   Oman: "OMN",
//   Pakistan: "PAK",
//   Panama: "PAN",
//   Pitcairn: "PCN",
//   Peru: "PER",
//   Philippines: "PHL",
//   Palau: "PLW",
//   "Papua New Guinea": "PNG",
//   Poland: "POL",
//   "Puerto Rico": "PRI",
//   "Korea (Democratic People's Republic of)": "PRK",
//   Portugal: "PRT",
//   Paraguay: "PRY",
//   "Palestine, State of": "PSE",
//   "French Polynesia": "PYF",
//   Qatar: "QAT",
//   "Reunion !Réunion": "REU",
//   Romania: "ROU",
//   "Russian Federation": "RUS",
//   Rwanda: "RWA",
//   "Saudi Arabia": "SAU",
//   Sudan: "SDN",
//   Senegal: "SEN",
//   Singapore: "SGP",
//   "South Georgia and the South Sandwich Islands": "SGS",
//   "Saint Helena, Ascension and Tristan da Cunha": "SHN",
//   "Svalbard and Jan Mayen": "SJM",
//   "Solomon Islands": "SLB",
//   "Sierra Leone": "SLE",
//   "El Salvador": "SLV",
//   "San Marino": "SMR",
//   Somalia: "SOM",
//   "Saint Pierre and Miquelon": "SPM",
//   Serbia: "SRB",
//   "South Sudan": "SSD",
//   "Sao Tome and Principe": "STP",
//   Suriname: "SUR",
//   Slovakia: "SVK",
//   Slovenia: "SVN",
//   Sweden: "SWE",
//   Swaziland: "SWZ",
//   "Sint Maarten (Dutch part)": "SXM",
//   Seychelles: "SYC",
//   "Syrian Arab Republic": "SYR",
//   "Turks and Caicos Islands": "TCA",
//   Chad: "TCD",
//   Togo: "TGO",
//   Thailand: "THA",
//   Tajikistan: "TJK",
//   Tokelau: "TKL",
//   Turkmenistan: "TKM",
//   "Timor-Leste": "TLS",
//   Tonga: "TON",
//   "Trinidad and Tobago": "TTO",
//   Tunisia: "TUN",
//   Turkey: "TUR",
//   Tuvalu: "TUV",
//   "Taiwan, Province of China[a]": "TWN",
//   "Tanzania, United Republic of": "TZA",
//   Uganda: "UGA",
//   Ukraine: "UKR",
//   "United States Minor Outlying Islands": "UMI",
//   Uruguay: "URY",
//   "United States of America": "USA",
//   Uzbekistan: "UZB",
//   "Holy See": "VAT",
//   "Saint Vincent and the Grenadines": "VCT",
//   "Venezuela (Bolivarian Republic of)": "VEN",
//   "Virgin Islands (British)": "VGB",
//   "Virgin Islands (U.S.)": "VIR",
//   "Viet Nam": "VNM",
//   Vanuatu: "VUT",
//   "Wallis and Futuna": "WLF",
//   Samoa: "WSM",
//   Kosovo: "XKS",
//   Yemen: "YEM",
//   "South Africa": "ZAF",
//   Zambia: "ZMB",
//   Zimbabwe: "ZWE",
// };

// var States1 = {
//   ARE: {
//     Dubai: "Dubai",
//     "Dubai Jabel Ali": "Dubai-JBL",
//   },
//   ESP: {
//     "Calle Miguel Angel 16, 28010": "Madrid",
//   },
//   IRQ: {
//     Baghdad: "Baghdad",
//   },
//   POL: {
//     Koscierzyn: "Koscierzyn",
//     MAZOWIECKI: "MAZOWIECKI",
//   },
//   SDN: {
//     Khartoum: "Khartoum",
//   },
//   USA: {
//     Alaska: "AK",
//     Alabama: "AL",
//     Arkansas: "AR",
//     "American Samoa": "AS",
//     Arizona: "AZ",
//     California: "CA",
//     Colorado: "CO",
//     Connecticut: "CT",
//     "District of Columbia": "DC",
//     Delaware: "DE",
//     Florida: "FL",
//     "Federated States of Micronesia": "FM",
//     Georgia: "GA",
//     Guam: "GU",
//     Hawaii: "HI",
//     Iowa: "IA",
//     Idaho: "ID",
//     Illinois: "IL",
//     Indiana: "IN",
//     Kansas: "KS",
//     Kentucky: "KY",
//     Louisiana: "LA",
//     Massachusetts: "MA",
//     Maryland: "MD",
//     Maine: "ME",
//     "Marshall Islands": "MH",
//     Michigan: "MI",
//     Minnesota: "MN",
//     Missouri: "MO",
//     "Northern Mariana Islands": "MP",
//     Mississippi: "MS",
//     Montana: "MT",
//     "North Carolina": "NC",
//     "North Dakota": "ND",
//     Nebraska: "NE",
//     "New Hampshire": "NH",
//     "New Jersey": "NJ",
//     "New Mexico": "NM",
//     Nevada: "NV",
//     "New York": "NY",
//     Ohio: "OH",
//     Oklahoma: "OK",
//     Oregon: "OR",
//     Pennsylvania: "PA",
//     "Puerto Rico": "PR",
//     Palau: "PW",
//     "Rhode Island": "RI",
//     "South Carolina": "SC",
//     "South Dakota": "SD",
//     Tennesee: "TN",
//     Texas: "TX",
//     Utah: "UT",
//     Virginia: "VA",
//     "Virgin Islands": "VI",
//     Vermont: "VT",
//     Washington: "WA",
//     Wisconsin: "WI",
//     "West Virginia": "WV",
//     Wyoming: "WY",
//   },
// };
// var countriesWithStates = {};

// for (var countryName in countries1) {
//   var countryCode = countries1[countryName];
//   if (States1[countryCode]) {
//     countriesWithStates[countryCode] = States1[countryCode];
//   }
// }

// var countryCodesWithStates = Object.keys(countriesWithStates);
// console.log(countryCodesWithStates);
